id: A3A008630
title: A Prayer to Chöying Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.861797
  last_modified_at: 2022-03-01 05:23:36.861800
