id: A3A008630
title: 'The Tamboura of Devotion: A Prayer to Götsang Gönpo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.088702
  last_modified_at: 2022-03-01 05:23:37.088705
