id: A3A008630
title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.103656
  last_modified_at: 2022-03-01 05:23:37.103659
