id: A3A008630
title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
  Jamyang Khyentse Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.911870
  last_modified_at: 2022-03-01 05:23:36.911874
