id: A3A008630
title: Prayer Composed for Yakzé Tsewang Gyurme
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.945602
  last_modified_at: 2022-03-01 05:23:36.945605
