id: A3A008630
title: A Prayer to Yumka Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.879902
  last_modified_at: 2022-03-01 05:23:36.879906
