id: A3A008630
title: 'Great Drum of the Devas: A Prayer to the Dharma King Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.936653
  last_modified_at: 2022-03-01 05:23:36.936656
