id: A3A008630
title: 'The Moon’s Illusory Reflection to Gladden the Devoted: A Prayer to the Successive
  Rebirths'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.061808
  last_modified_at: 2022-03-01 05:23:37.061810
