id: A3A008630
title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the Liberational
  Life of the Omniscient Jamyang Khyentse Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.053399
  last_modified_at: 2022-03-01 05:23:37.053402
