id: A3A008630
title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.987585
  last_modified_at: 2022-03-01 05:23:36.987587
