id: A3A008630
title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All that
  Appears and Exists'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.108034
  last_modified_at: 2022-03-01 05:23:37.108037
