id: A3A008630
title: 'The Tree of Awakening: A Prayer to the Great Abbot Śāntarakṣita'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.101251
  last_modified_at: 2022-03-01 05:23:37.101254
