id: A3A008630
title: 'Cloud Banks of Blessings: A Brief Prayer to the Garland of Successive Rebirths'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.922330
  last_modified_at: 2022-03-01 05:23:36.922335
