id: A3A008630
title: 'The Hook of Compassion: A Prayer to the Garland of Successive Rebirths'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.044884
  last_modified_at: 2022-03-01 05:23:37.044886
