id: A3A008630
title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.994849
  last_modified_at: 2022-03-01 05:23:36.994851
