id: A3A008630
title: Prayer to Rigdzin Jatsön Nyingpo
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.997133
  last_modified_at: 2022-03-01 05:23:36.997136
