id: A3A008630
title: Prayer to Lord Marpa, Consort and Heirs
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.988908
  last_modified_at: 2022-03-01 05:23:36.988910
