id: A3A008630
title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.940996
  last_modified_at: 2022-03-01 05:23:36.940998
