id: A3A008630
title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.039296
  last_modified_at: 2022-03-01 05:23:37.039299
