id: A3A008630
title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.859004
  last_modified_at: 2022-03-01 05:23:36.859007
