id: A3A008630
title: Prayer for this Life, the Next and the Bardos
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.959144
  last_modified_at: 2022-03-01 05:23:36.959147
