id: A3A008630
title: Prayer to Khenpo Ngawang Palzang
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.985010
  last_modified_at: 2022-03-01 05:23:36.985013
