id: A3A008630
title: Prayer to the Siddha Virūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.020232
  last_modified_at: 2022-03-01 05:23:37.020234
