id: A3A008630
title: The Summoning of Blessings which Brings them Swift and Fast
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.081653
  last_modified_at: 2022-03-01 05:23:37.081656
