id: A3A008630
title: 'The Liberating Guide: A Prayer to Gyalwa Yangönpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.046412
  last_modified_at: 2022-03-01 05:23:37.046415
