id: A3A008630
title: 'Waves in A Sea of Devotion: A Prayer to the Garland of Zurmang Trungpa Rinpoche
  Incarnations'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.111090
  last_modified_at: 2022-03-01 05:23:37.111093
