id: A3A008630
title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.027111
  last_modified_at: 2022-03-01 05:23:37.027113
