id: A3A008630
title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
  the Four Empowerments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.865628
  last_modified_at: 2022-03-01 05:23:36.865631
