id: A3A008630
title: Prayer to Tārā, Combined with Her Mantra
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.007988
  last_modified_at: 2022-03-01 05:23:37.007991
