id: A3A008630
title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King of the
  Dralas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.080445
  last_modified_at: 2022-03-01 05:23:37.080448
