id: A3A008630
title: A Dzogchen Tögal Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.847127
  last_modified_at: 2022-03-01 05:23:36.847130
