id: A3A008630
title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.975739
  last_modified_at: 2022-03-01 05:23:36.975742
