id: A3A008630
title: 'The Sunlight of Blessings: A Prayer'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.083192
  last_modified_at: 2022-03-01 05:23:37.083194
