id: A3A008630
title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.013051
  last_modified_at: 2022-03-01 05:23:37.013053
