id: A3A008630
title: Prayer to Gyarong Khandro Dechen Wangmo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.969208
  last_modified_at: 2022-03-01 05:23:36.969210
