id: A3A008630
title: Brief Succession of Lives Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.920554
  last_modified_at: 2022-03-01 05:23:36.920559
