id: A3A008630
title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on the Meaning
  of the Great Perfection'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.069388
  last_modified_at: 2022-03-01 05:23:37.069392
