id: A3A008630
title: Aspiration to Follow the Gurus of the Ngor Tradition
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.916835
  last_modified_at: 2022-03-01 05:23:36.916837
