id: A3A008630
title: Prayer to Buddha AmitÄbha
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.964371
  last_modified_at: 2022-03-01 05:23:36.964373
