id: A3A008630
title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha Thangtong
  Gyalpo's Lifetime as Bhikṣu Padma Karpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.105841
  last_modified_at: 2022-03-01 05:23:37.105843
