id: A3A008630
title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen Rabjam'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.049290
  last_modified_at: 2022-03-01 05:23:37.049293
