id: A3A008630
title: 'Averting Obstructive Circumstances: A Prayer to Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.919048
  last_modified_at: 2022-03-01 05:23:36.919051
