id: A3A008630
title: Regularly Recitable Prayer to the Root Guru, Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.028926
  last_modified_at: 2022-03-01 05:23:37.028929
