id: A3A008630
title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the VidyÄdhara
  Gurus of the Three Lineages'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.064584
  last_modified_at: 2022-03-01 05:23:37.064587
