id: A3A008630
title: 'Song of Devotion: A Prayer to Lord Marpa Lotsāwa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.031892
  last_modified_at: 2022-03-01 05:23:37.031895
