id: A3A008630
title: A Supplication to Noble Tārā, The Wish-Fulfilling Cornucopia
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.914289
  last_modified_at: 2022-03-01 05:23:36.914292
