id: A3A008630
title: Prayer to Mañjuśrī
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.991790
  last_modified_at: 2022-03-01 05:23:36.991792
