id: A3A008630
title: 'The Treasury of Blessings: A Prayer to Recall the Sublime Masters who Showed
  Great Kindness to the Land of Snows'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.099519
  last_modified_at: 2022-03-01 05:23:37.099522
