id: A3A008630
title: Three Prayers from the Earth Pig Year
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.104866
  last_modified_at: 2022-03-01 05:23:37.104869
