id: A3A008630
title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.944226
  last_modified_at: 2022-03-01 05:23:36.944229
