id: A3A008630
title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.966751
  last_modified_at: 2022-03-01 05:23:36.966753
