id: A3A008630
title: A Prayer to the Vidyādhara Gurus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.907812
  last_modified_at: 2022-03-01 05:23:36.907819
