id: A3A008630
title: Prayer Written for Lama Chödrak
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.953408
  last_modified_at: 2022-03-01 05:23:36.953412
