id: A3A008630
title: A Prayer to Khandro Yeshé Tsogyal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.866723
  last_modified_at: 2022-03-01 05:23:36.866726
