id: A3A008630
title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled Kindness,
  Drodül Pawo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.035848
  last_modified_at: 2022-03-01 05:23:37.035850
