id: A3A008630
title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.924428
  last_modified_at: 2022-03-01 05:23:36.924431
