id: A3A008630
title: Prayer for the Dawning of Clear Light
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.954983
  last_modified_at: 2022-03-01 05:23:36.954986
