id: A3A008630
title: Essence of All the Buddhas of Past, Present and Future
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.928894
  last_modified_at: 2022-03-01 05:23:36.928897
