id: A3A008630
title: In Praise of the Eight Siddhas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.938626
  last_modified_at: 2022-03-01 05:23:36.938629
