id: A3A008630
title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.084508
  last_modified_at: 2022-03-01 05:23:37.084511
