id: A3A008630
title: 'Eliminator of Suffering: A Prayer to the Venerable and Exalted Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.926426
  last_modified_at: 2022-03-01 05:23:36.926428
