id: A3A008630
title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.878271
  last_modified_at: 2022-03-01 05:23:36.878274
