id: A3A008630
title: Prayer to His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.970721
  last_modified_at: 2022-03-01 05:23:36.970723
