id: A3A008630
title: Prayer to the Great Paṇḍita Vimalamitra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.014132
  last_modified_at: 2022-03-01 05:23:37.014135
