id: A3A008630
title: Prayer on the Occasion of the Reading Transmission for the Omniscient King
  of Dharma's Thirteen-Volume Collected Writings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.960443
  last_modified_at: 2022-03-01 05:23:36.960446
