id: A3A008630
title: Prayer to Tsarchen Losal Gyatso
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.006339
  last_modified_at: 2022-03-01 05:23:37.006342
