id: A3A008630
title: Essence and Embodiment of All the Buddhas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.927774
  last_modified_at: 2022-03-01 05:23:36.927777
