id: A3A008630
title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master Jamgön
  Kongtrul Thaye'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.056029
  last_modified_at: 2022-03-01 05:23:37.056032
