id: A3A008630
title: Prayer to My Root Guru, Jamyang Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.992956
  last_modified_at: 2022-03-01 05:23:36.992959
