id: A3A008630
title: Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.027977
  last_modified_at: 2022-03-01 05:23:37.027979
