id: A3A008630
title: Prayer to Khandro Tsering Chödrön
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.982955
  last_modified_at: 2022-03-01 05:23:36.982957
