id: A3A008630
title: 'The Revelling Ocean of Blessings: A Prayer to Tsarchen Dorje Chang'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.073752
  last_modified_at: 2022-03-01 05:23:37.073755
