id: A3A008630
title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:36.951136
  last_modified_at: 2022-03-01 05:23:36.951139
