id: A3A008630
title: Prayer to the Successive Lives of the Great Trulshik 'Destroyer of Delusion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:23:37.022052
  last_modified_at: 2022-03-01 05:23:37.022055
